### ISSUE TITLE
Mettre en cache le fetchRegistryApps & fetchInstalledApps

### ISSUE THREAD

**Issue by Narkfr** [cozy/cozy-store#20]
Actuellement le fetchInstalledApps lance une requête à chaque navigation entre /myapps /discovery /application, alors que la réponse reste la même.

Proposition :
Mettre en cache ces requêtes, à minima pour la session courante, et effacé le cache uniquement en cas d'installation / désinstallation d'une app.

**Comment by gregorylegarec** [comment]
@goldoraf est-ce que redux-cozy-client intègre déjà un mécanisme de cache ?

**Comment by Narkfr** [comment]
On peut se passer du cache en fait, juste vérifier si il y a quelque chose dans le store avant un fetch
Si oui > on fetch pas
Si non > on fetch

**Comment by goldoraf** [comment]
@gregorylegarec pas encore, mais c'est prévu pour bientôt

**Comment by nono** [comment]
Le problème a été réglé, je ferme l'issue.
