### ISSUE TITLE
Title of the page

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-store#274]
cozy-store instead of Cozy Store.

Screenshot from fab.

![image](https://user-images.githubusercontent.com/465582/41987585-e53af02e-7a39-11e8-9c21-567d298a6952.png)

If you use cozy-scripts the problem should be fixed by https://github.com/CPatchane/create-cozy-app/pull/627

**Comment by CPatchane** [comment]
This is issue is now fixe, thanks @ptbrowne 👍
